arguments = ARGV
from = arguments[0] #file.rb -> file.rbc
output = arguments[1] #file.rbc -> file.exe
from_stripped = from.split('.').first
from_rbc = from_stripped + '.rbc'
# arguments 2 .. n -> source folders to add
source_folders = arguments[2..-1].join(' ')

puts 'Sheathing down...'
puts "Compiling #{from} to #{"./bin/from_stripped"}.rbc"
byte_code = RubyVM::InstructionSequence.compile_file(from)
File.binwrite("./bin/#{from_stripped}.rbc", Marshal.dump(byte_code.to_binary))
puts 'Done!'

# multi-line puts

puts 'Sheathing up...'
# strip filename from to
output_ruby_compile_file = "#{from_stripped}.tmp.rb"

puts "Outputting to #{output_ruby_compile_file}"
File.open(output_ruby_compile_file, 'w') do |file|
  file.puts "generated by sheathup.rb/.exe"
  file.puts "arguments = ARGV"
  file.puts "from = arguments[0]"
  file.puts "byte_code = File.binread(\"./bin/#{from_rbc}\")"
  file.puts "iseq = RubyVM::InstructionSequence.load_from_binary(Marshal.load(byte_code))"
  file.puts "iseq.eval unless defined? Ocra"
end

puts 'Done!'

puts "Compiling #{output_ruby_compile_file} to #{from_stripped}.exe"

# compile to exe
`ocran  #{output_ruby_compile_file} bin #{source_folders} --verbose --add-all-core --chdir-first --output #{output}`



